package com.navilive.android.model

import java.util.Locale

// Generated from shared/product-rules.json by scripts/generate-shared-product-rules.py.
// Do not edit this file manually.

data class SearchDistanceBand(
    val maxMeters: Int,
    val bonus: Int,
)

object SharedProductRules {

    object Navigation {
        val countdownMilestonesMeters: List<Int> = listOf(10, 20, 30, 40, 50, 100, 200, 300, 400)
        val countdownMilestonesSeconds: List<Int> = listOf(10, 20, 30, 40, 50)

        const val maneuverAdvanceAccuracyMinMeters: Float = 10.0f
        const val maneuverAdvanceAccuracyMaxMeters: Float = 20.0f
        const val maneuverAdvanceMultiplier: Double = 1.5

        const val offRouteAccuracyMinMeters: Float = 15.0f
        const val offRouteAccuracyMaxMeters: Float = 32.0f
        const val offRouteMultiplier: Float = 1.8f
        const val offRouteMinimumThresholdMeters: Int = 30

        const val immediateInstructionAccuracyMinMeters: Float = 5.0f
        const val immediateInstructionAccuracyMaxMeters: Float = 8.0f
        const val immediateInstructionThresholdMinMeters: Int = 5
        const val immediateInstructionThresholdMaxMeters: Int = 8

        const val autoRecalculateCooldownMs: Long = 15000L
    }

    object Search {
        const val includeGlobalFallbackIfFewerThan: Int = 3
        const val nearbyBonus: Int = 650
        const val nearbyLimit: Int = 10
        const val globalLimit: Int = 16
        const val resultLimit: Int = 8
        const val nearbyRadiusKm: Double = 12.0
        const val globalRadiusKm: Double = 60.0
        const val viewBoxMinimumCosine: Double = 0.2
        const val walkingEtaMetersPerMinute: Double = 75.0

        const val exactNameScore: Int = 600
        const val prefixNameScore: Int = 320
        const val exactTokenScore: Int = 220
        const val prefixTokenScore: Int = 180
        const val containsTokenScore: Int = 140
        const val addressTokenScore: Int = 60
        const val distancePenaltyDivisorMeters: Int = 2500
        const val distancePenaltyCap: Int = 120

        val distanceBands: List<SearchDistanceBand> = listOf(
            SearchDistanceBand(maxMeters = 500, bonus = 700),
            SearchDistanceBand(maxMeters = 2000, bonus = 550),
            SearchDistanceBand(maxMeters = 10000, bonus = 350),
            SearchDistanceBand(maxMeters = 50000, bonus = 120)
        )
    }

    object Address {
        val streetPriorityKeys: List<String> = listOf("road", "pedestrian", "footway", "path", "cycleway", "residential")
        val localityPriorityKeys: List<String> = listOf("city", "town", "village", "hamlet", "municipality", "suburb", "neighbourhood", "quarter", "city_district")
        val regionPriorityKeys: List<String> = listOf("state", "region", "state_district", "county")
        const val appendCountryIfFewerThanParts: Int = 2
        const val houseNumberPatternRaw: String = "^\\d+[\\p{L}]?(?:[/-]\\d+[\\p{L}]?)?$"
        const val leadingHouseNumberStreetPatternRaw: String = "^(\\d+[\\p{L}]?(?:[/-]\\d+[\\p{L}]?)?)\\s+(.+)$"
        val houseNumberPattern: Regex = Regex(houseNumberPatternRaw)
        val leadingHouseNumberStreetPattern: Regex = Regex(leadingHouseNumberStreetPatternRaw)
    }

    object Instructions {
        val supportedModifiers: Set<String> = setOf("left", "right", "slight left", "slight right", "sharp left", "sharp right", "straight", "uturn")

        fun normalizeModifier(value: String): String = value.trim().lowercase(Locale.ROOT)
    }
}
