from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPO_ROOT / "shared" / "product-rules.json"
ANDROID_OUTPUT = (
    REPO_ROOT
    / "android"
    / "app"
    / "src"
    / "main"
    / "java"
    / "com"
    / "navilive"
    / "android"
    / "model"
    / "SharedProductRules.kt"
)
IOS_OUTPUT = (
    REPO_ROOT
    / "native-ios"
    / "NaviLive"
    / "Sources"
    / "Core"
    / "Models"
    / "SharedProductRules.swift"
)


def read_rules() -> dict:
    return json.loads(SOURCE_PATH.read_text(encoding="utf-8"))


def escape_for_code_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_android(rules: dict) -> str:
    navigation = rules["navigation"]
    stabilization = navigation["locationStabilization"]
    projection = navigation["routeProjection"]
    search = rules["search"]
    scoring = search["scoring"]
    address = rules["address"]
    instructions = rules["instructions"]

    countdown = ", ".join(str(value) for value in navigation["countdownMilestonesMeters"])
    countdown_seconds = ", ".join(str(value) for value in navigation["countdownMilestonesSeconds"])
    distance_bands = ",\n            ".join(
        f"SearchDistanceBand(maxMeters = {item['maxMeters']}, bonus = {item['bonus']})"
        for item in scoring["distanceBands"]
    )
    street_keys = ", ".join(f'"{value}"' for value in address["streetPriorityKeys"])
    locality_keys = ", ".join(f'"{value}"' for value in address["localityPriorityKeys"])
    region_keys = ", ".join(f'"{value}"' for value in address["regionPriorityKeys"])
    supported_modifiers = ", ".join(f'"{value}"' for value in instructions["supportedModifiers"])

    return f"""package com.navilive.android.model

import java.util.Locale

// Generated from shared/product-rules.json by scripts/generate-shared-product-rules.py.
// Do not edit this file manually.

data class SearchDistanceBand(
    val maxMeters: Int,
    val bonus: Int,
)

object SharedProductRules {{

    object Navigation {{
        val countdownMilestonesMeters: List<Int> = listOf({countdown})
        val countdownMilestonesSeconds: List<Int> = listOf({countdown_seconds})

        const val maneuverAdvanceAccuracyMinMeters: Float = {navigation['maneuverAdvance']['accuracyMinMeters']}f
        const val maneuverAdvanceAccuracyMaxMeters: Float = {navigation['maneuverAdvance']['accuracyMaxMeters']}f
        const val maneuverAdvanceMultiplier: Double = {navigation['maneuverAdvance']['multiplier']}

        const val offRouteAccuracyMinMeters: Float = {navigation['offRoute']['accuracyMinMeters']}f
        const val offRouteAccuracyMaxMeters: Float = {navigation['offRoute']['accuracyMaxMeters']}f
        const val offRouteMultiplier: Float = {navigation['offRoute']['multiplier']}f
        const val offRouteMinimumThresholdMeters: Int = {navigation['offRoute']['minimumThresholdMeters']}

        const val immediateInstructionAccuracyMinMeters: Float = {navigation['immediateInstruction']['accuracyMinMeters']}f
        const val immediateInstructionAccuracyMaxMeters: Float = {navigation['immediateInstruction']['accuracyMaxMeters']}f
        const val immediateInstructionThresholdMinMeters: Int = {navigation['immediateInstruction']['thresholdMinMeters']}
        const val immediateInstructionThresholdMaxMeters: Int = {navigation['immediateInstruction']['thresholdMaxMeters']}

        const val guidanceLeadMeters: Int = {navigation['guidanceLeadMeters']}
        const val gpsReliableAccuracyMeters: Float = {navigation['gpsReliableAccuracyMeters']}f
        const val gpsWeakAccuracyMeters: Float = {navigation['gpsWeakAccuracyMeters']}f
        const val arrivalAccuracyMinMeters: Float = {navigation['arrival']['accuracyMinMeters']}f
        const val arrivalAccuracyMaxMeters: Float = {navigation['arrival']['accuracyMaxMeters']}f
        const val arrivalAccuracyMultiplier: Double = {navigation['arrival']['multiplier']}
        const val assistantFreshLocationMaxAgeMs: Long = {navigation['assistantFreshLocationMaxAgeMs']}L

        const val autoRecalculateCooldownMs: Long = {navigation['autoRecalculateCooldownMs']}L

        const val routeProjectionBacktrackToleranceMeters: Double = {projection['backtrackToleranceMeters']}
        const val routeProjectionLookAheadToleranceMeters: Double = {projection['lookAheadToleranceMeters']}
        const val routeProjectionDeviationLookAheadMeters: Double = {projection['deviationLookAheadMeters']}
        const val routeProjectionCourseUseMinimumSpeedMetersPerSecond: Double = {projection['courseUseMinimumSpeedMetersPerSecond']}
        const val routeProjectionCourseMaximumAccuracyMeters: Float = {projection['courseMaximumAccuracyMeters']}f
        const val routeProjectionCourseMismatchPenaltyMeters: Double = {projection['courseMismatchPenaltyMeters']}

        const val locationStabilizationStaleResetMs: Long = {stabilization['staleResetMs']}L
        const val locationStabilizationMaxUsableAccuracyMeters: Float = {stabilization['maxUsableAccuracyMeters']}f
        const val locationStabilizationStationaryDistanceMeters: Double = {stabilization['stationaryDistanceMeters']}
        const val locationStabilizationStationaryAccuracyMultiplier: Double = {stabilization['stationaryAccuracyMultiplier']}
        const val locationStabilizationStationaryMaxDistanceMeters: Double = {stabilization['stationaryMaxDistanceMeters']}
        const val locationStabilizationMaxWalkingSpeedMetersPerSecond: Double = {stabilization['maxWalkingSpeedMetersPerSecond']}
        const val locationStabilizationJumpDistanceMinMeters: Double = {stabilization['jumpDistanceMinMeters']}
        const val locationStabilizationJumpAccuracyMultiplier: Double = {stabilization['jumpAccuracyMultiplier']}
        const val locationStabilizationSmoothingMaxDistanceMeters: Double = {stabilization['smoothingMaxDistanceMeters']}
        const val locationStabilizationSmoothingAlphaWhenAccuracyImproves: Double = {stabilization['smoothingAlphaWhenAccuracyImproves']}
        const val locationStabilizationSmoothingAlphaWhenAccuracyWorsens: Double = {stabilization['smoothingAlphaWhenAccuracyWorsens']}
    }}

    object Search {{
        const val includeGlobalFallbackIfFewerThan: Int = {search['includeGlobalFallbackIfFewerThan']}
        const val nearbyBonus: Int = {search['nearbyBonus']}
        const val nearbyLimit: Int = {search['nearbyLimit']}
        const val globalLimit: Int = {search['globalLimit']}
        const val resultLimit: Int = {search['resultLimit']}
        const val minimumResultLimit: Int = {search['minimumResultLimit']}
        const val maximumResultLimit: Int = {search['maximumResultLimit']}
        const val defaultRadiusKm: Int = {search['defaultRadiusKm']}
        const val minimumRadiusKm: Int = {search['minimumRadiusKm']}
        const val maximumRadiusKm: Int = {search['maximumRadiusKm']}
        const val nearbyRadiusKm: Double = {search['nearbyRadiusKm']}
        const val globalRadiusKm: Double = {search['globalRadiusKm']}
        const val viewBoxMinimumCosine: Double = {search['viewBoxMinimumCosine']}
        const val walkingEtaMetersPerMinute: Double = {search['walkingEtaMetersPerMinute']}
        const val localPoiRadiusMeters: Int = {search['localPoiRadiusMeters']}
        const val localPoiLimit: Int = {search['localPoiLimit']}
        const val overpassTimeoutSeconds: Int = {search['overpassTimeoutSeconds']}

        const val exactNameScore: Int = {scoring['exactName']}
        const val prefixNameScore: Int = {scoring['prefixName']}
        const val exactTokenScore: Int = {scoring['exactToken']}
        const val prefixTokenScore: Int = {scoring['prefixToken']}
        const val containsTokenScore: Int = {scoring['containsToken']}
        const val addressTokenScore: Int = {scoring['addressToken']}
        const val localPoiScore: Int = {scoring['localPoi']}
        const val categoryMatchScore: Int = {scoring['categoryMatch']}
        const val railQueryStationScore: Int = {scoring['railQueryStation']}
        const val railQueryBusStopPenalty: Int = {scoring['railQueryBusStopPenalty']}
        const val distancePenaltyDivisorMeters: Int = {scoring['distancePenaltyDivisorMeters']}
        const val distancePenaltyCap: Int = {scoring['distancePenaltyCap']}

        val distanceBands: List<SearchDistanceBand> = listOf(
            {distance_bands}
        )
    }}

    object Address {{
        val streetPriorityKeys: List<String> = listOf({street_keys})
        val localityPriorityKeys: List<String> = listOf({locality_keys})
        val regionPriorityKeys: List<String> = listOf({region_keys})
        const val appendCountryIfFewerThanParts: Int = {address['appendCountryIfFewerThanParts']}
        const val houseNumberPatternRaw: String = "{escape_for_code_string(address['houseNumberPattern'])}"
        const val leadingHouseNumberStreetPatternRaw: String = "{escape_for_code_string(address['leadingHouseNumberStreetPattern'])}"
        val houseNumberPattern: Regex = Regex(houseNumberPatternRaw)
        val leadingHouseNumberStreetPattern: Regex = Regex(leadingHouseNumberStreetPatternRaw)
    }}

    object Instructions {{
        val supportedModifiers: Set<String> = setOf({supported_modifiers})

        fun normalizeModifier(value: String): String = value.trim().lowercase(Locale.ROOT)
    }}
}}
"""


def render_ios(rules: dict) -> str:
    navigation = rules["navigation"]
    stabilization = navigation["locationStabilization"]
    projection = navigation["routeProjection"]
    search = rules["search"]
    scoring = search["scoring"]
    address = rules["address"]
    instructions = rules["instructions"]

    countdown = ", ".join(str(value) for value in navigation["countdownMilestonesMeters"])
    countdown_seconds = ", ".join(str(value) for value in navigation["countdownMilestonesSeconds"])
    distance_bands = ",\n      ".join(
        f"SearchDistanceBand(maxMeters: {item['maxMeters']}, bonus: {item['bonus']})"
        for item in scoring["distanceBands"]
    )
    street_keys = ", ".join(f'"{value}"' for value in address["streetPriorityKeys"])
    locality_keys = ", ".join(f'"{value}"' for value in address["localityPriorityKeys"])
    region_keys = ", ".join(f'"{value}"' for value in address["regionPriorityKeys"])
    supported_modifiers = ", ".join(f'"{value}"' for value in instructions["supportedModifiers"])

    return f"""import Foundation

// Generated from shared/product-rules.json by scripts/generate-shared-product-rules.py.
// Do not edit this file manually.

enum SharedProductRules {{
  struct SearchDistanceBand {{
    let maxMeters: Int
    let bonus: Int
  }}

  enum Navigation {{
    static let countdownMilestonesMeters: [Int] = [{countdown}]
    static let countdownMilestonesSeconds: [Int] = [{countdown_seconds}]

    static let maneuverAdvanceAccuracyMinMeters: Double = {navigation['maneuverAdvance']['accuracyMinMeters']}
    static let maneuverAdvanceAccuracyMaxMeters: Double = {navigation['maneuverAdvance']['accuracyMaxMeters']}
    static let maneuverAdvanceMultiplier: Double = {navigation['maneuverAdvance']['multiplier']}

    static let offRouteAccuracyMinMeters: Double = {navigation['offRoute']['accuracyMinMeters']}
    static let offRouteAccuracyMaxMeters: Double = {navigation['offRoute']['accuracyMaxMeters']}
    static let offRouteMultiplier: Double = {navigation['offRoute']['multiplier']}
    static let offRouteMinimumThresholdMeters: Int = {navigation['offRoute']['minimumThresholdMeters']}

    static let immediateInstructionAccuracyMinMeters: Double = {navigation['immediateInstruction']['accuracyMinMeters']}
    static let immediateInstructionAccuracyMaxMeters: Double = {navigation['immediateInstruction']['accuracyMaxMeters']}
    static let immediateInstructionThresholdMinMeters: Int = {navigation['immediateInstruction']['thresholdMinMeters']}
    static let immediateInstructionThresholdMaxMeters: Int = {navigation['immediateInstruction']['thresholdMaxMeters']}

    static let guidanceLeadMeters: Int = {navigation['guidanceLeadMeters']}
    static let gpsReliableAccuracyMeters: Double = {navigation['gpsReliableAccuracyMeters']}
    static let gpsWeakAccuracyMeters: Double = {navigation['gpsWeakAccuracyMeters']}
    static let arrivalAccuracyMinMeters: Double = {navigation['arrival']['accuracyMinMeters']}
    static let arrivalAccuracyMaxMeters: Double = {navigation['arrival']['accuracyMaxMeters']}
    static let arrivalAccuracyMultiplier: Double = {navigation['arrival']['multiplier']}
    static let assistantFreshLocationMaxAgeMs: Int = {navigation['assistantFreshLocationMaxAgeMs']}

    static let autoRecalculateCooldownMs: Int = {navigation['autoRecalculateCooldownMs']}

    static let routeProjectionBacktrackToleranceMeters: Double = {projection['backtrackToleranceMeters']}
    static let routeProjectionLookAheadToleranceMeters: Double = {projection['lookAheadToleranceMeters']}
    static let routeProjectionDeviationLookAheadMeters: Double = {projection['deviationLookAheadMeters']}
    static let routeProjectionCourseUseMinimumSpeedMetersPerSecond: Double = {projection['courseUseMinimumSpeedMetersPerSecond']}
    static let routeProjectionCourseMaximumAccuracyMeters: Double = {projection['courseMaximumAccuracyMeters']}
    static let routeProjectionCourseMismatchPenaltyMeters: Double = {projection['courseMismatchPenaltyMeters']}

    static let locationStabilizationStaleResetMs: Int = {stabilization['staleResetMs']}
    static let locationStabilizationMaxUsableAccuracyMeters: Double = {stabilization['maxUsableAccuracyMeters']}
    static let locationStabilizationStationaryDistanceMeters: Double = {stabilization['stationaryDistanceMeters']}
    static let locationStabilizationStationaryAccuracyMultiplier: Double = {stabilization['stationaryAccuracyMultiplier']}
    static let locationStabilizationStationaryMaxDistanceMeters: Double = {stabilization['stationaryMaxDistanceMeters']}
    static let locationStabilizationMaxWalkingSpeedMetersPerSecond: Double = {stabilization['maxWalkingSpeedMetersPerSecond']}
    static let locationStabilizationJumpDistanceMinMeters: Double = {stabilization['jumpDistanceMinMeters']}
    static let locationStabilizationJumpAccuracyMultiplier: Double = {stabilization['jumpAccuracyMultiplier']}
    static let locationStabilizationSmoothingMaxDistanceMeters: Double = {stabilization['smoothingMaxDistanceMeters']}
    static let locationStabilizationSmoothingAlphaWhenAccuracyImproves: Double = {stabilization['smoothingAlphaWhenAccuracyImproves']}
    static let locationStabilizationSmoothingAlphaWhenAccuracyWorsens: Double = {stabilization['smoothingAlphaWhenAccuracyWorsens']}
  }}

  enum Search {{
    static let includeGlobalFallbackIfFewerThan: Int = {search['includeGlobalFallbackIfFewerThan']}
    static let nearbyBonus: Int = {search['nearbyBonus']}
    static let nearbyLimit: Int = {search['nearbyLimit']}
    static let globalLimit: Int = {search['globalLimit']}
    static let resultLimit: Int = {search['resultLimit']}
    static let minimumResultLimit: Int = {search['minimumResultLimit']}
    static let maximumResultLimit: Int = {search['maximumResultLimit']}
    static let defaultRadiusKm: Int = {search['defaultRadiusKm']}
    static let minimumRadiusKm: Int = {search['minimumRadiusKm']}
    static let maximumRadiusKm: Int = {search['maximumRadiusKm']}
    static let nearbyRadiusKm: Double = {search['nearbyRadiusKm']}
    static let globalRadiusKm: Double = {search['globalRadiusKm']}
    static let viewBoxMinimumCosine: Double = {search['viewBoxMinimumCosine']}
    static let walkingEtaMetersPerMinute: Double = {search['walkingEtaMetersPerMinute']}
    static let localPoiRadiusMeters: Int = {search['localPoiRadiusMeters']}
    static let localPoiLimit: Int = {search['localPoiLimit']}
    static let overpassTimeoutSeconds: Int = {search['overpassTimeoutSeconds']}

    static let exactNameScore: Int = {scoring['exactName']}
    static let prefixNameScore: Int = {scoring['prefixName']}
    static let exactTokenScore: Int = {scoring['exactToken']}
    static let prefixTokenScore: Int = {scoring['prefixToken']}
    static let containsTokenScore: Int = {scoring['containsToken']}
    static let addressTokenScore: Int = {scoring['addressToken']}
    static let localPoiScore: Int = {scoring['localPoi']}
    static let categoryMatchScore: Int = {scoring['categoryMatch']}
    static let railQueryStationScore: Int = {scoring['railQueryStation']}
    static let railQueryBusStopPenalty: Int = {scoring['railQueryBusStopPenalty']}
    static let distancePenaltyDivisorMeters: Int = {scoring['distancePenaltyDivisorMeters']}
    static let distancePenaltyCap: Int = {scoring['distancePenaltyCap']}

    static let distanceBands: [SearchDistanceBand] = [
      {distance_bands}
    ]
  }}

  enum Address {{
    static let streetPriorityKeys: [String] = [{street_keys}]
    static let localityPriorityKeys: [String] = [{locality_keys}]
    static let regionPriorityKeys: [String] = [{region_keys}]
    static let appendCountryIfFewerThanParts: Int = {address['appendCountryIfFewerThanParts']}
    static let houseNumberPattern: String = "{escape_for_code_string(address['houseNumberPattern'])}"
    static let leadingHouseNumberStreetPattern: String = "{escape_for_code_string(address['leadingHouseNumberStreetPattern'])}"
  }}

  enum Instructions {{
    static let supportedModifiers: Set<String> = [{supported_modifiers}]

    static func normalizeModifier(_ value: String) -> String {{
      value.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }}
  }}
}}
"""


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text.rstrip() + "\n")


def main() -> None:
    rules = read_rules()
    write_text(ANDROID_OUTPUT, render_android(rules))
    write_text(IOS_OUTPUT, render_ios(rules))
    print(f"Generated {ANDROID_OUTPUT}")
    print(f"Generated {IOS_OUTPUT}")


if __name__ == "__main__":
    main()
