import Foundation

// Generated from shared/product-rules.json by scripts/generate-shared-product-rules.py.
// Do not edit this file manually.

enum SharedProductRules {
  struct SearchDistanceBand {
    let maxMeters: Int
    let bonus: Int
  }

  enum Navigation {
    static let countdownMilestonesMeters: [Int] = [10, 20, 30, 40, 50, 100, 200, 300, 400]
    static let countdownMilestonesSeconds: [Int] = [10, 20, 30, 40, 50]

    static let maneuverAdvanceAccuracyMinMeters: Double = 10.0
    static let maneuverAdvanceAccuracyMaxMeters: Double = 20.0
    static let maneuverAdvanceMultiplier: Double = 1.5

    static let offRouteAccuracyMinMeters: Double = 10.0
    static let offRouteAccuracyMaxMeters: Double = 30.0
    static let offRouteMultiplier: Double = 1.4
    static let offRouteMinimumThresholdMeters: Int = 25

    static let immediateInstructionAccuracyMinMeters: Double = 5.0
    static let immediateInstructionAccuracyMaxMeters: Double = 8.0
    static let immediateInstructionThresholdMinMeters: Int = 5
    static let immediateInstructionThresholdMaxMeters: Int = 8

    static let guidanceLeadMeters: Int = 7
    static let gpsReliableAccuracyMeters: Double = 20.0
    static let gpsWeakAccuracyMeters: Double = 75
    static let arrivalAccuracyMinMeters: Double = 8.0
    static let arrivalAccuracyMaxMeters: Double = 18.0
    static let arrivalAccuracyMultiplier: Double = 2.0
    static let assistantFreshLocationMaxAgeMs: Int = 15000

    static let autoRecalculateCooldownMs: Int = 6000

    static let routeProjectionBacktrackToleranceMeters: Double = 18.0
    static let routeProjectionLookAheadToleranceMeters: Double = 30.0
    static let routeProjectionDeviationLookAheadMeters: Double = 120.0
    static let routeProjectionCourseUseMinimumSpeedMetersPerSecond: Double = 0.8
    static let routeProjectionCourseMaximumAccuracyMeters: Double = 35.0
    static let routeProjectionCourseMismatchPenaltyMeters: Double = 18.0

    static let locationStabilizationStaleResetMs: Int = 20000
    static let locationStabilizationMaxUsableAccuracyMeters: Double = 100.0
    static let locationStabilizationStationaryDistanceMeters: Double = 4.0
    static let locationStabilizationStationaryAccuracyMultiplier: Double = 0.45
    static let locationStabilizationStationaryMaxDistanceMeters: Double = 12.0
    static let locationStabilizationMaxWalkingSpeedMetersPerSecond: Double = 4.2
    static let locationStabilizationJumpDistanceMinMeters: Double = 25.0
    static let locationStabilizationJumpAccuracyMultiplier: Double = 1.25
    static let locationStabilizationSmoothingMaxDistanceMeters: Double = 35.0
    static let locationStabilizationSmoothingAlphaWhenAccuracyImproves: Double = 0.55
    static let locationStabilizationSmoothingAlphaWhenAccuracyWorsens: Double = 0.35
  }

  enum Search {
    static let includeGlobalFallbackIfFewerThan: Int = 3
    static let nearbyBonus: Int = 650
    static let nearbyLimit: Int = 20
    static let globalLimit: Int = 16
    static let resultLimit: Int = 10
    static let minimumResultLimit: Int = 3
    static let maximumResultLimit: Int = 30
    static let defaultRadiusKm: Int = 3
    static let minimumRadiusKm: Int = 1
    static let maximumRadiusKm: Int = 10
    static let nearbyRadiusKm: Double = 2.0
    static let globalRadiusKm: Double = 25.0
    static let viewBoxMinimumCosine: Double = 0.2
    static let walkingEtaMetersPerMinute: Double = 75.0
    static let localPoiRadiusMeters: Int = 3000
    static let localPoiLimit: Int = 40
    static let overpassTimeoutSeconds: Int = 12

    static let exactNameScore: Int = 600
    static let prefixNameScore: Int = 320
    static let exactTokenScore: Int = 220
    static let prefixTokenScore: Int = 180
    static let containsTokenScore: Int = 140
    static let addressTokenScore: Int = 60
    static let localPoiScore: Int = 900
    static let categoryMatchScore: Int = 850
    static let railQueryStationScore: Int = 1000
    static let railQueryBusStopPenalty: Int = 450
    static let distancePenaltyDivisorMeters: Int = 2500
    static let distancePenaltyCap: Int = 120

    static let distanceBands: [SearchDistanceBand] = [
      SearchDistanceBand(maxMeters: 500, bonus: 700),
      SearchDistanceBand(maxMeters: 2000, bonus: 550),
      SearchDistanceBand(maxMeters: 10000, bonus: 350),
      SearchDistanceBand(maxMeters: 50000, bonus: 120)
    ]
  }

  enum Address {
    static let streetPriorityKeys: [String] = ["road", "pedestrian", "footway", "path", "cycleway", "residential"]
    static let localityPriorityKeys: [String] = ["city", "town", "village", "hamlet", "municipality", "suburb", "neighbourhood", "quarter", "city_district"]
    static let regionPriorityKeys: [String] = ["state", "region", "state_district", "county"]
    static let appendCountryIfFewerThanParts: Int = 2
    static let houseNumberPattern: String = "^\\d+[\\p{L}]?(?:[/-]\\d+[\\p{L}]?)?$"
    static let leadingHouseNumberStreetPattern: String = "^(\\d+[\\p{L}]?(?:[/-]\\d+[\\p{L}]?)?)\\s+(.+)$"
  }

  enum Instructions {
    static let supportedModifiers: Set<String> = ["left", "right", "slight left", "slight right", "sharp left", "sharp right", "straight", "uturn"]

    static func normalizeModifier(_ value: String) -> String {
      value.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }
  }
}
